server:
  port: 7001
eureka:
  client:
    register-with-eureka: false   #是否将自己注册到eureka中
    fetch-registry: false   #是否从eureka中获取信息
    service-url:
      defualtZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: eureka